version: "3"

# Compose file for local testing

services:
  cocoda:
    build: .
    volumes:
      # Contains built Cocoda instances
      - ./data/cocoda:/www/cocoda
      # Contains custom configs
      - ./data/configs:/configs
      # Optionally mount Cocoda repository so it won't need to be cloned again when the container is recreated
      - ./data/cocoda.git:/root/cocoda/
      # Optionally mount start.mjs script for development so that we can edit it without rebuilding the container
      - ./start.mjs:/root/start.mjs
    ports:
      - 8091:80
    environment:
      # Tags or branches to be built with default configuration
      - TAGS=dev
      # Serve instances under subpath "/cocoda/"
      - USE_SUBPATH=true
      # Optional port (default is 80)
      # - PORT=8091
    # restart: unless-stopped
